name: Run CI

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: read

jobs:
  gitctl:
    name: gitctl
    permissions:
      contents: read
      pull-requests: write
      checks: write
      security-events: write
      packages: write
      actions: read
    uses: ./.github/workflows/reusable-go-ci.yaml
    with:
      name: gitctl
      module: .
      run_check_generated_files: false
      ko_build_path: "main.go"
      lint_fail_on_issues: true
