# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: go-build-test
on:
  push:
    branches:
      - "main"
      - "feature-**"
      - "release-**"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # pin@5.5.0
      with:
        go-version: stable

    - name: Set up gotestfmt
      uses: gotesttools/gotestfmt-action@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        set -euo pipefail
        go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt

    - name: Upload test log
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # pin@v4.6.2
      if: always()
      with:
        name: test-log
        path: /tmp/gotest.log
        if-no-files-found: error
